### ISSUE TITLE
Training code for 'Adversarially trained feature encoder'?

### ISSUE THREAD

**Issue by kadarsh22** [mmoayeri/spuriosity-rankings#1]
Thank you for your excellent work. I am currently working on analyzing medical data and need to identify spurious features. I understand that the IMAGNET-trained adversarial feature encoder might not be sufficient for this task. Could you please provide the code to train an adversarial feature encoder?

**Comment by mmoayeri** [comment]
Hi Kadarsh, thanks for your interest! Here is a good repo for adversarially training classifiers: https://github.com/MadryLab/robustness.  I believe you will just need to format your dataset following their abstract class, and then adversarial training can be done with a single call (with a config specifiying hyperparameters like the threat model and budget you would like).
